### ISSUE TITLE
Error on Cordova 3.6 (Android)

### ISSUE THREAD

**Issue by enricodeleo** [guilhermefarias/cordova-exif#7]
Hi!
I can't get this plugin to work. Tried different solutions but nothing happened. Here is my console.log taken with Weinre.

processMessage failed: Error: TypeError: Cannot call method 'toString' of undefined
processMessage failed: Stack: TypeError: Cannot call method 'toString' of undefined
    at Console._generic (http://192.168.1.170:8080/target/target-script-min.js:1503:27)
    at Console.log (http://192.168.1.170:8080/target/target-script-min.js:1519:13)
    at Object.callback (file:///android_asset/www/controllers/UploadController.js:15:15)
    at Object.handleBinaryImage (file:///android_asset/www/vendor/exif.js:62:18)
    at [object Object].<anonymous> (file:///android_asset/www/vendor/exif.js:57:18)
    at file:///android_asset/www/plugins/org.apache.cordova.file/www/FileReader.js:288:20
    at Object.callbackFromNative (file:///android_asset/www/cordova.js:293:54)
    at processMessage (file:///android_asset/www/cordova.js:1054:21)
    at Function.processMessages (file:///android_asset/www/cordova.js:1091:13)
    at pollOnce (file:///android_asset/www/cordova.js:956:17)
processMessage failed: Message: S01 File1459578791 S/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgY [...]

the last line seems to be the base64 image.

Any help would be much appreciated :)

**Comment by enricodeleo** [comment]
up :)
